spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #MySQL does not support sequences, so ...
      use-new-id-generator-mappings: false
    show-sql: true
    ddl: auto-none
  datasource:
    url: jdbc:mysql://localhost:3306/datalogger
    username: data_writer
    password: pwd_writer

server:
  servlet:
    contextPath: /muddyserver
  port: 9000
  ssl:
    key-store: classpath:chris.p12
    key-store-password: aardvark
    key-store-type: pkcs12
    key-alias: chris
    key-password: aardvark
    enabled: true

logging:
  level:
    org:
      springframework.web: TRACE
      hibernate: INFO

debug: false
